# Even Fibonacci numbers
# Problem 2
# Published on Friday, 19th October 2001, 06:00 pm; Solved by 446922; Difficulty rating: 5%
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

  # create a hash with values set to the fibonacci sequence
  fibonacci = Hash.new{ |h,k| h[k] = k < 2 ? k : h[k-1] + h[k-2] }

  # find the sum of all even fibonacci number below 4000000
  fibonacci_sums = 0
  i = 1
  while fibonacci[i] <= 4000000
    fibonacci_sums += fibonacci[i] if fibonacci[i] % 2 == 0
    i += 1
  end
  answer = fibonacci_sums
  puts answer
